INSERT INTO product VALUES (DEFAULT, '3/4" Spindle Roughing Gouge', 116.00);
INSERT INTO product VALUES (DEFAULT, '1/4" Spindle Gouge', 49.00);
INSERT INTO product VALUES (DEFAULT, '3/8" Spindle Gouge', 58.00);
INSERT INTO product VALUES (DEFAULT, '1/2" Spindle Gouge', 64.50);
INSERT INTO product VALUES (DEFAULT, '3/8" Detail Gouge', 63.50);
INSERT INTO product VALUES (DEFAULT, '1/2" Detail Gouge', 69.00);
INSERT INTO product VALUES (DEFAULT, '3/16" Parting Tool', 83.00);
INSERT INTO product VALUES (DEFAULT, '3/4" Skew Chisel', 69.00);
INSERT INTO product VALUES (DEFAULT, '1/4" Bowl Gouge', 74.50);
INSERT INTO product VALUES (DEFAULT, '3/8" Bowl Gouge', 83.00);
INSERT INTO product VALUES (DEFAULT, '1/2" Bowl Gouge', 108.00);
INSERT INTO product VALUES (DEFAULT, '1/2" Ellsworth Gouge', 142.50);
INSERT INTO product VALUES (DEFAULT, '3/4" Square-Nose Scraper', 66.00);
INSERT INTO product VALUES (DEFAULT, '3/4" Round-Nose Scraper', 66.00);
