DROP TABLE product IF EXISTS;

CREATE TABLE product (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
price FLOAT NOT NULL
);

DROP TABLE order_table IF EXISTS;
CREATE TABLE order_table (
id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY 
);

DROP TABLE order_item IF EXISTS;
CREATE TABLE order_item (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
order_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
quantity INTEGER NOT NULL,
FOREIGN KEY (order_id) REFERENCES order_table(id),
FOREIGN KEY (product_id) REFERENCES product(id),
);